-- 巧克力
STRINGS.NAMES.CAVE_CHOCOLATE = "士力架"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CAVE_CHOCOLATE = "士力架，横扫饥饿，做回自己！"

-- 浆果丛互换
STRINGS.RECIPE_DESC.DUG_BERRYBUSH = "浆果灌木丛"
STRINGS.RECIPE_DESC.DUG_BERRYBUSH2 = "三叶浆果丛"
STRINGS.RECIPE_DESC.DUG_BERRYBUSH_JUICY = "多汁浆果丛"
STRINGS.RECIPE_DESC.DUG_GRASS = "长草根"
STRINGS.RECIPE_DESC.DUG_SAPLING = "小树苗"

-- 逐风之刃
STRINGS.NAMES.CHASETHEWIND = "逐风之刃"
STRINGS.RECIPE_DESC.CHASETHEWIND = "给予金子可升级！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CHASETHEWIND = "风啊，赐予我力量吧！"

-- 皮肤法杖
STRINGS.NAMES.SKINSTAFF= "皮肤法杖"
STRINGS.RECIPE_DESC.SKINSTAFF = "皮肤法杖"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SKINSTAFF= "皮肤法杖！"

-- 月亮石法杖
STRINGS.NAMES.MOON_STAFF= "皮肤法杖"
STRINGS.RECIPE_DESC.MOON_STAFF = "皮肤法杖"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOON_STAFF= "皮肤法杖！"

STRINGS.RECIPE_DESC.ANCIENT_ALTAR = "制造一个远古科技塔"

STRINGS.NAMES.TZ_ICESWORD = "神器·剑魂"
STRINGS.RECIPE_DESC.TZ_ICESWORD = "曾经通宵的回忆..."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_ICESWORD = "羁绊"

STRINGS.NAMES.OLDFISH_AXE = "神器·汲取"
STRINGS.RECIPE_DESC.OLDFISH_AXE = "渴望祭品..."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.OLDFISH_AXE = "谁能挡我！"

STRINGS.NAMES.DRAGON_HEART_GEM = "暮光琥珀"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGON_HEART_GEM = "这是巨龙的心脏！"
STRINGS.NAMES.BEEQUEEN_HEART_GEM = "烁光玉髓"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BEEQUEEN_HEART_GEM = "奇怪，上面一点蜂蜜都没沾上"
STRINGS.NAMES.MALBATROSS_HEART_GEM = "风暴水晶"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MALBATROSS_HEART_GEM = "它来自大海"

STRINGS.NAMES.PHOENIXSPEAR_FIRE = "火焰凤凰剑"
STRINGS.RECIPE_DESC.PHOENIXSPEAR_FIRE = "火焰之力"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PHOENIXSPEAR_FIRE = "也许将他们融合在一起会更好用"

STRINGS.NAMES.PHOENIXSPEAR_ICE = "冰霜凤凰剑"
STRINGS.RECIPE_DESC.PHOENIXSPEAR_ICE = "冰霜之力"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PHOENIXSPEAR_ICE = "也许将他们融合在一起会更好用"

STRINGS.NAMES.FLYINGHUNTER = "神器·斩翼者"
STRINGS.RECIPE_DESC.FLYINGHUNTER = "只有真正的强者才配拥有这把剑！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FLYINGHUNTER = "它现在还不那么趁手"

STRINGS.NAMES.ARMOROBSIDIAN = "黑曜石甲"
STRINGS.RECIPE_DESC.ARMOROBSIDIAN = "最坚硬的护甲！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMOROBSIDIAN = "坚如磐石"
STRINGS.NAMES.OBSIDIAN = "黑曜石"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.OBSIDIAN = "这块奇怪的石头来自哪儿呢"

STRINGS.NAMES.OBSIDIANFIREPIT = "黑曜石火坑"
STRINGS.RECIPE_DESC.OBSIDIANFIREPIT = "照亮一整个家！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.OBSIDIANFIREPIT = "玩火 ....... 自焚"

STRINGS.NAMES.DUG_COFFEEBUSH = "咖啡丛"
STRINGS.RECIPE_DESC.DUG_COFFEEBUSH = "咖啡丛！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_COFFEEBUSH = "咖啡丛"

STRINGS.NAMES.COFFEEBUSH = "咖啡丛"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEEBUSH = "咖啡丛"

STRINGS.NAMES.COFFEE = "咖啡"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEE = "咖啡"

STRINGS.NAMES.COFFEEBEANS = "咖啡豆"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEEBEANS = "咖啡豆"

STRINGS.NAMES.COFFEEBEANS_COOKED = "烤咖啡豆"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEEBEANS_COOKED = "烤咖啡豆"

STRINGS.NAMES.FEIJOADA = "八宝饭"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FEIJOADA = "八宝饭"

STRINGS.NAMES.JELLYBUG = "豆虫"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JELLYBUG = "豆虫"

STRINGS.NAMES.JELLYBUG_COOKED = "烤豆虫"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JELLYBUG_COOKED = "烤豆虫"

STRINGS.NAMES.TOMATO_SOUP = "番茄蛋汤"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOMATO_SOUP = "这就是我梦寐以求的！"

STRINGS.NAMES.NEW_REEDS = "芦苇"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.NEW_REEDS = "歪比巴卜"

STRINGS.NAMES.DUG_REEDS = "芦苇根"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_REEDS = "我应该把它带到更有用的地方."

STRINGS.RECIPE_DESC.BLUEGEM = "蓝宝石"

STRINGS.RECIPE_DESC.REDGEM = "红宝石"

STRINGS.NAMES.FLOWERBOX = "花盒"
STRINGS.RECIPE_DESC.FLOWERBOX = "利用花瓣来装饰它！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FLOWERBOX = {
	GENERIC = "光秃秃的，或许我可以找到更好的装饰品",
	PETALS = "真棒！它现在看起来好多了~",
	EVIL = "我讨厌它，快拿走！",
	CAVE = "真是个明智的选择"
}

STRINGS.NAMES.PUGALISK_FOUNTAIN = "发光喷泉"
STRINGS.RECIPE_DESC.PUGALISK_FOUNTAIN = "令人赏心悦目"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PUGALISK_FOUNTAIN = {
	PRE = "它正在充能",
	FULL = "太......高......了.....",
	PST = "它正在消逝",
	EMPTY = "期待下一次相聚"
}

STRINGS.NAMES.WATERDROP = "生命之水"
STRINGS.NAMES.LIFEPLANT = "生命之花"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.WATERDROP = "你认为是水吗？"				-- wilson
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIFEPLANT = "它当然喜欢看自己"

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WATERDROP = "多么有活力的小种子啊"			-- maxwell
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.LIFEPLANT = "我还是喜欢玫瑰"

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WATERDROP = "是神奇的水种子"				-- wolfgang
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.LIFEPLANT = "是美丽的花朵"

STRINGS.CHARACTERS.WX78.DESCRIBE.WATERDROP = "我敌人的婴儿"						-- wx78
STRINGS.CHARACTERS.WX78.DESCRIBE.LIFEPLANT = "它在我埋葬我的敌人时生长"

STRINGS.CHARACTERS.WILLOW.DESCRIBE.WATERDROP = "真应该是个火焰"					-- willow
STRINGS.CHARACTERS.WILLOW.DESCRIBE.LIFEPLANT = "我觉得还行"

STRINGS.CHARACTERS.WENDY.DESCRIBE.WATERDROP = "这凄凉的生活中的一滴生命"		-- wendy
STRINGS.CHARACTERS.WENDY.DESCRIBE.LIFEPLANT = "它渴望另一个生命"

STRINGS.CHARACTERS.WOODIE.DESCRIBE.WATERDROP = "每一个生命都要下一点雨"			-- woodie
STRINGS.CHARACTERS.WOODIE.DESCRIBE.LIFEPLANT = "漂亮的小花"

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WATERDROP = "它看起来像种子"			-- wickerbottom
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.LIFEPLANT = "水仙诗意。相当漂亮的一个"

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WATERDROP = "一滴水，被弗雷娅碰了一下"	-- wathgrithr
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.LIFEPLANT = "它赋予生命"

STRINGS.CHARACTERS.WEBBER.DESCRIBE.WATERDROP = "额。。。是水滴还是种子？"		-- webber
STRINGS.CHARACTERS.WEBBER.DESCRIBE.LIFEPLANT = "真漂亮！"

STRINGS.CHARACTERS.WINONA.DESCRIBE.WATERDROP = "这是水，不过我可不想喝它"		-- winona
STRINGS.CHARACTERS.WINONA.DESCRIBE.LIFEPLANT = "放在我旁边会影响我工作的"

STRINGS.CHARACTERS.WORTOX.DESCRIBE.WATERDROP = "这里面也有灵魂"					-- wortox
STRINGS.CHARACTERS.WORTOX.DESCRIBE.LIFEPLANT = "看起来这就是它的真身"

STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.WATERDROP = "为了土壤"						-- wormwood
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.LIFEPLANT = "活泼的朋友"

STRINGS.CHARACTERS.WARLY.DESCRIBE.WATERDROP = "生命之水"						-- warly
STRINGS.CHARACTERS.WARLY.DESCRIBE.LIFEPLANT = "它看起来很饿"

STRINGS.NAMES.SKULL_CHEST = "末影箱"
STRINGS.RECIPE_DESC.SKULL_CHEST = "这是......魔法吗?"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SKULL_CHEST = {
	CONNECT = "现在他们连通了",
	ALONE = "他需要另一个末影箱才能连通",
}

STRINGS.NAMES.PERSONAL_CHEST = "私人箱子"
STRINGS.RECIPE_DESC.PERSONAL_CHEST = "捍卫你的隐私！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PERSONAL_CHEST = "熊孩子的敌人！"

STRINGS.NAMES.SWEET_POTATO = "甘薯"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SWEET_POTATO = "这个比胡萝卜甜"

STRINGS.NAMES.SWEET_POTATO_PLANTED = "甘薯"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SWEET_POTATO_PLANTED = "我还能说什么呢"

STRINGS.NAMES.SWEET_POTATO_COOKED = "烤甘薯"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SWEET_POTATO_COOKED = "真香！"

STRINGS.NAMES.TREEROOT = "树根"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TREEROOT = "粗壮的树根"

STRINGS.NAMES.TURF_PIGRUINS = "猪镇地砖"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_PIGRUINS = "猪镇地砖"

STRINGS.NAMES.TURF_QUAGMIRE_GATEWAY = "暴食地皮1"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_QUAGMIRE_GATEWAY = "暴食地皮1"

STRINGS.NAMES.TURF_BEACH = "沙滩地皮"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_BEACH = "沙滩地皮"

STRINGS.NAMES.MOONROCK_CHIP = "月亮石"
STRINGS.RECIPE_DESC.MOONROCK_CHIP = "月亮石！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONROCK_CHIP = "月亮石！"

STRINGS.NAMES.MOON_ARMOR = "月亮石甲"
STRINGS.RECIPE_DESC.MOON_ARMOR = "月亮石甲！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOON_ARMOR = "月亮石甲！"

STRINGS.NAMES.SHARKITTEN = "小虎鲨"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARKITTEN = "嘿，亲爱的，你妈妈呢？"

STRINGS.NAMES.TIGERSHARK = "虎鲨"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TIGERSHARK = "虎鲨"

STRINGS.NAMES.SHARKITTENSPAWNER = "虎鲨巢穴"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARKITTENSPAWNER = "虎鲨巢穴"

STRINGS.NAMES.SHARK_GILLS = "虎鲨皮"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARK_GILLS = "鳃从水中除去氧气。很棒的生物力学！"

STRINGS.NAMES.SHARK_FIN = "虎鲨鳍"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARK_FIN = "鱼鳍掉了。"

STRINGS.NAMES.FISH_RAW = "大鱼肉"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_RAW = "一大块鱼肉."

STRINGS.NAMES.TIGEREYE = "虎鲨之眼"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TIGEREYE = "虎鲨的眼睛"

STRINGS.NAMES.FISH_MED_COOKED = "鱼排"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FISH_MED_COOKED = "它看起来真的很好吃。"

STRINGS.NAMES.RAWLING = "罗琳"
STRINGS.RECIPE_DESC.RAWLING = "吹哨！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAWLING = "嘿，伙计！来一场沙滩排球怎么样？"

STRINGS.NAMES.CONCH = "神奇海螺"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CONCH = "海螺姑娘在哪里？"
